Symbol Table
CasperKjaerhus/SAL pull request #6
Opened 2021-04-29 10:34 UTC by CasperKjaerhus

2021-04-29 10:34 UTC, CasperKjaerhus commented on Antlr/Test_Parser_src/Test_Parser/Tests/SymbolTableTest.txt
> +string poo;
💩 ?

2021-04-29 10:37 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/Parser/ASTNode.cs
> +using SALShell.CodeGen;
Why?

2021-04-29 10:38 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/Parser/ASTVisitor.cs
> +            return default;
Øøøh virker det her?

2021-04-29 10:38 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/Parser/Nodes/FunctionDeclarationAstNode.cs
> +using SALShell.CodeGen;
Why?

2021-04-29 10:38 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/Parser/Nodes/ExprAstNode.cs
> +using SALShell.CodeGen;
Why?

2021-04-29 10:38 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/Parser/Nodes/ParameterListAstNode.cs
> +using SALShell.CodeGen;
grr

2021-04-29 10:40 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/Parser/Nodes/IdAstNode.cs
> +using SALShell.CodeGen;
xd

2021-04-29 10:44 UTC, anesheim-uni commented on Antlr/Test_Parser_src/Test_Parser/Tests/SymbolTableTest.txt
> +string poo;
+1

2021-04-29 10:44 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/DeclTypeInfo.cs
> +        IToken arraySize { get; }
Nok en god ide at omformatter det til et egentlig tal her?

2021-04-29 10:46 UTC, anesheim-uni commented on Shell/SALShell/SALShell/CodeGen/CodeEmitter.cs
> +            streamW.WriteLine($"for (int {numberOfElements} : {ArrayName})");
ligner ikke et ino eller c++ for loop?

2021-04-29 10:56 UTC, anesheim-uni reviewed
Meget enig med Cleth - efter request skal vi fikse type

2021-04-29 11:27 UTC, leafantsky requested changes

2021-04-29 11:27 UTC, leafantsky commented on Shell/SALShell/SALShell/SymbolTable/FuncTypeInfo.cs
> +            string funcString = "Function declaration taking the paremeters: ";
parameters*

2021-04-29 11:27 UTC, leafantsky commented on Shell/SALShell/SALShell/SymbolTable/DeclTypeInfo.cs
> +        IToken arraySize { get; }
Slettes eller blive?

2021-04-29 11:27 UTC, leafantsky commented on Shell/SALShell/SALShell/SymbolTable/IdTypeInfo.cs
> +        IToken idName { get; }
field efter constructor smh

2021-04-29 11:27 UTC, leafantsky commented on Shell/SALShell/SALShell/SymbolTable/Scope.cs
> +        public int Depth { get; }
field efter constructor

2021-04-29 11:27 UTC, leafantsky commented on Shell/SALShell/SALShell/SymbolTable/Symbol.cs
> +        public string SymbolName { get; }
xd placement

2021-04-29 11:27 UTC, leafantsky commented on Shell/SALShell/SALShell/SymbolTable/Scope.cs
> +            this.scopeName = scopeName;
sjovt mix

2021-04-29 11:27 UTC, leafantsky commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +        //THIS SYMBOL TABLE PROBABLY HAVE A VERY BAD SPACE AND TIME COMPLEXITY BUT ¯\_(ツ)_/¯
Nice troldpeter

2021-04-29 11:36 UTC, KasperLHP commented on Shell/SALShell/SALShell/SymbolTable/TypeInfo.cs
> +        public IToken Type { get; }
Fields efter constructor? kys

2021-04-29 11:36 UTC, KasperLHP commented on Shell/SALShell/SALShell/SymbolTable/Scope.cs
> +            this.scopeName = scopeName;
this. bruger du til at differentierer mellem constructor param og dit field fordi de har samme navn, men så gør du ikke det ved parent? burde man ikke stick til én convention (undskyld søren, ved ikke hvad jeg ellers skal finde)

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/FuncCallTypeInfo.cs
> +}
Er function calls en del af symbol table?

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/Scope.cs
> +            this.Depth = Depth;
this. nogle steder og ikke andre steder?

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/Scope.cs
> +        public Scope(Scope parent, string scopeName, int Depth)
Depth skal være med lille her

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +        //THIS SYMBOL TABLE PROBABLY HAVE A VERY BAD SPACE AND TIME COMPLEXITY BUT ¯\_(ツ)_/¯
xd

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +    class SymbolTableActual : ISymbolTable<Symbol, TypeInfo, Scope>
Virkelig dårlig navn til class ?

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +            Depth--;
Comments til det her kunne nok være godt

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +            return ScopeDisplay[ScopeDisplay.FindIndex(x => x.scopeName == ScopeName)].symbols.Any(x => x.SymbolName == symbolName);
Hvorfor ikke bare ScopeDisplay.find() i stedet for at først finde index, og så access igennem array?

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableVisitor.cs
> +            return new AssignmentTypeInfo(idNode.Type);
Brug visitor i stedet for typecast

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableVisitor.cs
> +            return new DeclTypeInfo(id.Type, id.ArraySize);
visitor i stedet for typecast

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableVisitor.cs
> +            ParameterListAstNode Paraminfo = (ParameterListAstNode)node.Parameters;
visitor i stedet for typecast

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/IdTypeInfo.cs
> +        bool isReference { get; }
Skal symbol table holde styr på referencer?

2021-05-04 11:34 UTC, CasperKjaerhus commented on Antlr/Test_Parser_src/Test_Parser/Tests/BoolsAndStrings.txt
> +
F

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/ISymbolTable.cs
> +    interface ISymbolTable<T, K>
Måske en god kommentar her omkring hvad T og K er

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/Scope.cs
> +            this.scopeName = scopeName;
Tell him

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +    class SymbolTableActual : ISymbolTable<Symbol, TypeInfo>
Generelt skal der flere kommentarer på symbol table. Den er ret 'magisk' fordi den springer frem og tilbage med hvor scopeindex og jeg ved ikke hvad bliver sat

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +    class SymbolTableActual : ISymbolTable<Symbol, TypeInfo>
Navn på class skal ændres imo

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableBuilder.cs
> +        int switchCount = 0;
please brug private keyword

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableBuilder.cs
> +                    IdAstNode Idinfo = (IdAstNode)funcCallRef.FunctionId;
type conversion av av av

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableBuilder.cs
> +                    IdAstNode dclId = (IdAstNode)dclNode.Id;
ooooooooooooooof

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableVisitor.cs
> +            IdAstNode id = (IdAstNode)node.Id;
Brug visitor i stedet for typecast

2021-05-04 11:34 UTC, CasperKjaerhus commented on Antlr/Test_Parser_src/Test_Parser/Tests/BoolsAndStrings.txt
> +﻿unction main(number strLength) returns void begin
fix

2021-05-04 11:34 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/Symbol.cs
> +        }
Er tom constructor needed?

2021-05-04 11:43 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/FuncCallTypeInfo.cs
> +}
De bliver ikke gemt i symbol-tablet, men bliver brugt til at tjekke om der kan blive gjort kald til den refererede funktion i CheckFunctionReferences() metoden :^)

2021-05-04 11:45 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +    class SymbolTableActual : ISymbolTable<Symbol, TypeInfo, Scope>
Enig, det blev også done on a whim

2021-05-04 12:00 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/Symbol.cs
> +        }
næh

2021-05-04 12:01 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableVisitor.cs
> +            IdAstNode id = (IdAstNode)node.Id;
Visitor returner ikke det jeg skal bruge fra noden desværre, så skulle jeg lave en ny visitor :/

2021-05-04 12:01 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableBuilder.cs
> +                    IdAstNode dclId = (IdAstNode)dclNode.Id;
Visitor returner ikke det jeg skal bruge fra noden desværre :/

2021-05-04 12:01 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableBuilder.cs
> +                    IdAstNode Idinfo = (IdAstNode)funcCallRef.FunctionId;
Visitor returner ikke det jeg skal bruge fra noden desværre :/

2021-05-04 12:05 UTC, CasperKjaerhus commented on Shell/SALShell/SALShell/SymbolTable/Symbol.cs
> +        }
slet så

2021-05-05 07:26 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +            Depth--;
Outdated 👍

2021-05-05 07:26 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/SymbolTableActual.cs
> +            return ScopeDisplay[ScopeDisplay.FindIndex(x => x.scopeName == ScopeName)].symbols.Any(x => x.SymbolName == symbolName);
ved jeg faktisk ikke, er fixed nu :)

2021-05-05 08:38 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/IdTypeInfo.cs
> +        bool isReference { get; }
referencer bliver ikke gemt i symbol table

2021-05-05 08:38 UTC, polter1337 commented on Antlr/Test_Parser_src/Test_Parser/Tests/BoolsAndStrings.txt
> +
also fixed

2021-05-05 08:41 UTC, polter1337 commented on Shell/SALShell/SALShell/SymbolTable/ISymbolTable.cs
> +    interface ISymbolTable<T, K>
Done

2021-05-05 08:45 UTC, merged